<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7luVZb4\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7luVZb4/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container7luVZb4.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container7luVZb4\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container7luVZb4\appAppKernelProdContainer([
    'container.build_hash' => '7luVZb4',
    'container.build_id' => '31678f53',
    'container.build_time' => 1670430113,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7luVZb4');
