version: '3'

services:
    harzypotterzy_mariadb:
      image: mariadb:10
      container_name: harzypotterzy_mariadb
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: harzypotterzy_db
        DB_USER: harzypotterzy
        DB_PASSWORD: harzypotterzy
        
      restart: on-failure
      ports:
      - 17259:3306

    harzypotterzy_presta:
      build: ../Presta
      container_name: harzypotterzy_presta
      restart: on-failure
      environment:
        PS_INSTALL_AUTO: 0
        PS_ERASE_DB: 0
        DB_SERVER: harzypotterzy_mariadb
        DB_USER: harzypotterzy
        DB_PASSWD: harzypotterzy
        DB_NAME: harzypotterzy_db
        PS_DEV_MODE: 0
        PS_DOMAIN: localhost:80
        PS_DOMAIN_SSL: localhost:443
        PS_ENABLE_SSL: 1
        PS_LANGUAGE: pl
        PS_COUNTRY: PL
        ADMIN_MAIL: pestap4k@gmail.com
        ADMIN_PASSWD: Asseco#123
      depends_on:
      - harzypotterzy_mariadb
      ports:
      - 80:80
      - 443:443