version: '2'

services:
  db:
    build: Maria
    container_name: MariaDB
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=Asseco#123
      - MYSQL_DATABASE=prestashop

  phpmyadmin:
    image: phpmyadmin
    container_name: phpMyAdmin
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:80

  prestashop:
    build: Presta
    container_name: Prestashop
    restart: on-failure
    depends_on:
    - db
    ports:
    - 80:80
    - 443:443
networks:
  default:
    driver: bridge
