version: '3'

services:
    harzypotterzy_mariadb:
      image: mariadb:10.11-rc
      container_name: harzypotterzy_mariadb
      environment:
        - MYSQL_ROOT_PASSWORD=Asseco#123
      restart: on-failure


    harzypotterzy_phpmyadmin:
      image: phpmyadmin
      container_name: phpMyAdmin
      restart: on-failure
      depends_on:
        - harzypotterzy_mariadb
      ports:
        - 8080:80

    harzypotterzy_presta:
      build: Presta
      container_name: HarzyPotterzy_presta
      restart: on-failure
      depends_on:
      - harzypotterzy_mariadb
      ports:
      - 80:80
      - 443:443
networks:
  default:
    driver: bridge
